import { CalendarEvent, Contact, Deal, Message, Task } from "./types";

export const contacts: Contact[] = [
  {
    id: "1",
    name: "Sarah Whitman",
    phone: "(512) 555-0142",
    email: "sarah.whitman@gmail.com",
    stage: "Showing",
    source: "Zillow",
    interest: "3BD in Round Rock, $400k-$450k",
    lastContact: "2026-08-21",
    activity: [
      { id: "a1", type: "call", summary: "Called to confirm Saturday showing at 214 Maple Ct.", date: "2026-08-21" },
      { id: "a2", type: "text", summary: "Sent listing link for 90 Oakwood Dr.", date: "2026-08-19" },
      { id: "a3", type: "note", summary: "Wants a big backyard, has two dogs.", date: "2026-08-14" },
    ],
  },
  {
    id: "2",
    name: "Marcus Reed",
    phone: "(512) 555-0198",
    email: "marcus.reed@outlook.com",
    stage: "New Lead",
    source: "Website",
    interest: "Investment property, duplex or triplex",
    lastContact: "2026-08-22",
    activity: [
      { id: "a4", type: "note", summary: "Submitted contact form asking about multi-family listings.", date: "2026-08-22" },
    ],
  },
  {
    id: "3",
    name: "The Alvarez Family",
    phone: "(512) 555-0176",
    email: "alvarez.family@icloud.com",
    stage: "Under Contract",
    source: "Referral",
    interest: "4BD in Cedar Park, closing in Sept",
    lastContact: "2026-08-20",
    activity: [
      { id: "a5", type: "email", summary: "Sent inspection report and next steps.", date: "2026-08-20" },
      { id: "a6", type: "call", summary: "Discussed appraisal timeline.", date: "2026-08-17" },
    ],
  },
  {
    id: "4",
    name: "Grace Kim",
    phone: "(512) 555-0113",
    email: "grace.kim@yahoo.com",
    stage: "Contacted",
    source: "Open House",
    interest: "Condo downtown, under $300k",
    lastContact: "2026-08-18",
    activity: [
      { id: "a7", type: "text", summary: "Following up after Sunday open house visit.", date: "2026-08-18" },
    ],
  },
  {
    id: "5",
    name: "Tom & Denise Barrett",
    phone: "(512) 555-0165",
    email: "barrett.family@gmail.com",
    stage: "Closed",
    source: "Referral",
    interest: "Closed on 5 Birchwood Ln in June",
    lastContact: "2026-06-30",
    activity: [
      { id: "a8", type: "note", summary: "Closed! Sent housewarming gift.", date: "2026-06-30" },
    ],
  },
  {
    id: "6",
    name: "Priya Natarajan",
    phone: "(512) 555-0121",
    email: "priya.n@gmail.com",
    stage: "Past Client",
    source: "Zillow",
    interest: "Bought starter home in 2024, may sell to upgrade",
    lastContact: "2026-05-02",
    activity: [
      { id: "a9", type: "call", summary: "Checked in, mentioned they may list next spring.", date: "2026-05-02" },
    ],
  },
];

export const messages: Message[] = [
  {
    id: "m1",
    contactId: "2",
    channel: "email",
    direction: "inbound",
    subject: "Investment property inquiry",
    body: "Hi, I saw your website and I'm interested in duplexes or triplexes in the area. Do you have any current listings that fit? Budget is flexible for the right property.",
    date: "2026-08-22",
    time: "3:40 PM",
  },
  {
    id: "m2",
    contactId: "4",
    channel: "text",
    direction: "inbound",
    body: "Hi! Following up - do you have any new condo listings under $300k downtown?",
    date: "2026-08-18",
    time: "11:02 AM",
  },
  {
    id: "m3",
    contactId: "3",
    channel: "email",
    direction: "outbound",
    subject: "Inspection Report + Next Steps",
    body: "Hi Alvarez family, attached is the inspection report from yesterday. Let's discuss the two items flagged before we move to appraisal.",
    date: "2026-08-20",
    time: "10:00 AM",
  },
  {
    id: "m4",
    contactId: "3",
    channel: "email",
    direction: "inbound",
    body: "Thanks for sending this over. We're okay with the roof note but want a quote on the water heater before signing off.",
    date: "2026-08-20",
    time: "2:15 PM",
  },
  {
    id: "m5",
    contactId: "3",
    channel: "email",
    direction: "outbound",
    body: "Sounds good, I'll get a quote from our contractor today and send it your way.",
    date: "2026-08-20",
    time: "2:30 PM",
  },
  {
    id: "m6",
    contactId: "1",
    channel: "text",
    direction: "inbound",
    body: "Hey! Just wanted to confirm we're still on for Saturday at 214 Maple Ct?",
    date: "2026-08-21",
    time: "9:14 AM",
  },
  {
    id: "m7",
    contactId: "1",
    channel: "text",
    direction: "outbound",
    body: "Yes! 11am, see you there 😊",
    date: "2026-08-21",
    time: "9:20 AM",
  },
  {
    id: "m8",
    contactId: "1",
    channel: "text",
    direction: "inbound",
    body: "Perfect, thank you!",
    date: "2026-08-21",
    time: "9:21 AM",
  },
];

export const events: CalendarEvent[] = [
  {
    id: "e1",
    contactId: "2",
    title: "Intro call",
    type: "call",
    date: "2026-08-23",
    time: "5:00 PM",
  },
  {
    id: "e2",
    title: "Open House — 90 Oakwood Dr",
    type: "open-house",
    date: "2026-08-22",
    time: "1:00 PM",
  },
  {
    id: "e3",
    contactId: "1",
    title: "Showing — 214 Maple Ct",
    type: "showing",
    date: "2026-08-24",
    time: "11:00 AM",
  },
  {
    id: "e4",
    contactId: "4",
    title: "Condo showing — 88 Congress Ave",
    type: "showing",
    date: "2026-08-25",
    time: "4:00 PM",
  },
  {
    id: "e5",
    contactId: "3",
    title: "Final walkthrough",
    type: "showing",
    date: "2026-08-27",
    time: "2:00 PM",
  },
  {
    id: "e6",
    contactId: "6",
    title: "Listing consultation",
    type: "listing-appointment",
    date: "2026-08-29",
    time: "1:00 PM",
  },
  {
    id: "e7",
    contactId: "3",
    title: "Closing",
    type: "closing",
    date: "2026-09-15",
    time: "10:00 AM",
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    contactId: "1",
    type: "buyer",
    stage: "Submitting Offers",
    title: "214 Maple Ct",
    value: 425000,
    closeDate: "2026-09-20",
    closeDateLabel: "Projected Close Date",
  },
  {
    id: "d2",
    contactId: "4",
    type: "buyer",
    stage: "Submitting Offers",
    title: "88 Congress Ave #12",
    value: 285000,
    closeDate: "2026-09-10",
    closeDateLabel: "Projected Close Date",
  },
  {
    id: "d3",
    contactId: "3",
    type: "buyer",
    stage: "Pending",
    title: "119 Chambers Creek Cr",
    value: 512000,
    closeDate: "2026-09-15",
    closeDateLabel: "Projected Close Date",
  },
  {
    id: "d4",
    contactId: "5",
    type: "buyer",
    stage: "Closed",
    title: "5 Birchwood Ln",
    value: 398000,
    closeDate: "2026-06-30",
    closeDateLabel: "Close Date",
  },
  {
    id: "d5",
    contactId: "6",
    type: "seller",
    stage: "Active Option Contract",
    title: "412 Sunset Terrace",
    value: 340000,
    closeDate: "2026-10-01",
    closeDateLabel: "Projected Close Date",
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    contactId: "1",
    title: "Confirm Saturday showing time",
    dueDate: "2026-08-23",
    createdAt: "2026-08-21",
    priority: "normal",
    done: false,
  },
  {
    id: "t2",
    contactId: "2",
    title: "Call new lead from website",
    dueDate: "2026-08-23",
    createdAt: "2026-08-22",
    priority: "urgent",
    done: false,
  },
  {
    id: "t3",
    contactId: "3",
    title: "Follow up on appraisal",
    dueDate: "2026-08-24",
    createdAt: "2026-08-20",
    priority: "normal",
    done: false,
  },
  {
    id: "t4",
    contactId: "4",
    title: "Send condo listings under $300k",
    dueDate: "2026-08-25",
    createdAt: "2026-08-18",
    priority: "normal",
    done: false,
  },
  {
    id: "t5",
    contactId: "6",
    title: "Check in about spring listing",
    dueDate: "2026-08-28",
    createdAt: "2026-08-16",
    priority: "normal",
    done: false,
  },
  {
    id: "t6",
    contactId: "4",
    title: "No response in 3 days — warm lead going cold",
    dueDate: "2026-08-21",
    createdAt: "2026-08-21",
    priority: "high",
    done: false,
  },
  {
    id: "t7",
    contactId: "1",
    title: "Showing feedback needs a reply today",
    dueDate: "2026-08-23",
    createdAt: "2026-08-23",
    priority: "urgent",
    done: false,
  },
  {
    id: "t8",
    contactId: "3",
    title: "Water heater quote — client is waiting on an answer",
    dueDate: "2026-08-22",
    createdAt: "2026-08-20",
    priority: "urgent",
    done: false,
  },
];
